### ISSUE TITLE
Add Open Source License

### ISSUE THREAD

**Issue by ascasson** [karazlab/swyya#33]
Hi! As a consumer, I do not know what license you intended to release this project under. Currently none is specified, which makes me less inclined to contribute. This may not be an open source project, however, and is instead source available only. If it is intended as open source, I'd recommend putting at the very least a LICENSE file with the correct license details. 🍻

**Comment by ehamamrah** [comment]
@ascasson thanks for informing us these details, we will be working on it and with that you contribute to Swyya and the community.

**Comment by ascasson** [comment]
@ehamamrah You're welcome. It's an easy thing to miss at the start. I like what you've done with the project! Thanks for your work :)

I'm happy to add the license if you would like. Do you know which license you want for the project?

**Comment by ehamamrah** [comment]
Not yet decided

**Comment by ehamamrah** [comment]
@ascasson Would you be able to work on it?

**Comment by ascasson** [comment]
You want me to figure out which license?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ascasson** [comment]
@ehamamrah I think it's important to know what you want from the project, and how you want others to relate to it. How much control you want to have over the product is also something to consider. These types of thoughts, along with others, will help drive which license to consider using.

**Comment by ehamamrah** [comment]
Working on It.
